#!/usr/bin/env python3

import json
import sys

def generate_genimage_cfg(partitions):
    cfg_content = '''
# This is a genimage configuration file auto generated by gen_imgcfg.py.
# require genimage version 16

image sdcard.img {
    hdimage {
        partition-table-type = gpt
    }
'''

    for partition in partitions:
        name = partition.get("name", "")
        src_size = partition.get("size", "")
        hidden = partition.get("hidden", False)
        visible = "true"
        if hidden == True:
            visible = "false"
        if src_size == "-":
            src_size = ""
        offset = partition.get("offset", "")
        image = partition.get("image", "")
        holes = partition.get("holes", "{}")


        cfg_content += f'''
    partition {name} {{
            image = "{image}"
            offset = "{offset}"
            size = "{src_size}"
            holes = {holes}
            in-partition-table = "{visible}"
    }}
        '''

    cfg_content += '''
}

'''

    return cfg_content

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("please input partitions json file")
        sys.exit(1)

    json_file = sys.argv[1]
    try:
        with open(json_file, 'r') as file:
            cfg_content = json.load(file)

        partitions = cfg_content["partitions"]
        genimage_cfg = generate_genimage_cfg(partitions)
    except FileNotFoundError:
        print(f"找不到文件: {json_file}")
    except json.JSONDecodeError as e:
        print(f"解析 JSON 时出错: {e}")

    with open("genimage.cfg", "w") as cfg_file:
        cfg_file.write(genimage_cfg)
    #print("genimage.cfg generated successfully.")
